trigger:
- master

jobs:
- job: Windows
  displayName: Build for Windows
  timeoutInMinutes: 10
  pool:
    vmImage: 'windows-latest'

  steps:
    - pwsh: .\Init.ps1
    - pwsh: .\Build.ps1

- job: Mac
  displayName: Build for OS X
  timeoutInMinutes: 10
  pool:
    vmImage: 'macOS-latest'

  steps:
    - pwsh: .\Init.ps1
    - pwsh: .\Build.ps1
