trigger:
- master

jobs:
- job: Windows
  displayName: Build for Windows
  timeoutInMinutes: 10
  pool:
    vmImage: 'windows-latest'

  steps:
    - pwsh: .\Init.ps1
      displayName: Initialize environment
    - pwsh: .\Build.ps1
      displayName: Build

# Azure Pipelines currently uses too old of a version of OS X for VCPKG.
# using Travis CI for now.
# - job: Mac
#   displayName: Build for OS X
#   timeoutInMinutes: 10
#   pool:
#     vmImage: 'macOS-latest'

#   steps:
#     - task: ShellScript@2
#       inputs:
#         scriptPath: ./init.sh
#       displayName: Initialize environment
#     - task: ShellScript@2
#       inputs:
#         scriptPath: ./build.sh
#       displayName: Build