trigger:
- master

variables:
  IsCIBuild: true

jobs:
- job: Windows
  displayName: Build for Windows
  timeoutInMinutes: 10
  pool:
    vmImage: 'windows-latest'

  steps:
    - pwsh: .\Init.ps1
      displayName: Initialize environment
    - pwsh: .\Build.ps1
      displayName: Build

- job: Mac
  displayName: Build for OS X
  timeoutInMinutes: 10
  pool:
    vmImage: 'macOS-latest'

  steps:
    - pwsh: sudo xcode-select --switch /Applications/XCode_9.4.1.app
      displayName: Select XCode version
    - task: ShellScript@2
      inputs:
        scriptPath: ./init.sh
      displayName: Initialize environment
    - task: ShellScript@2
      inputs:
        scriptPath: ./build.sh
      displayName: Build